# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 15:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.PositiveIntegerField(help_text='Utilice \xfanicamente n\xfameros', verbose_name='DNI')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=40, verbose_name='Apellido')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='G\xe9nero')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electr\xf3nico')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('approved', models.BooleanField()),
                ('error', models.BooleanField()),
            ],
        ),
    ]
